// <auto-generated />
using System;
using FilmRadar.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmRadar.Web.Migrations
{
    [DbContext(typeof(FilmRadarDbContext))]
    partial class FilmRadarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FilmRadar.Web.Domain.Genre", b =>
                {
                    b.Property<int>("TmdbGenreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TmdbGenreId");

                    b.ToTable("Genres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Genre_Id", "TmdbGenreId > 0");
                        });
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.SavedMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TmdbVoteAverage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("WatchedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "TmdbMovieId")
                        .IsUnique();

                    b.ToTable("SavedMovies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movie_Id", "TmdbMovieId > 0");

                            t.HasCheckConstraint("CK_Movie_Notes", "Notes IS NULL OR length(Notes) <= 1000");

                            t.HasCheckConstraint("CK_Movie_Rating", "PersonalRating IS NULL OR PersonalRating BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Movie_State", "(Status = 1 AND PersonalRating IS NULL AND WatchedOn IS NULL) OR (Status = 2 AND WatchedOn IS NOT NULL)");

                            t.HasCheckConstraint("CK_Movie_Status", "Status IN (1, 2)");

                            t.HasCheckConstraint("CK_Movie_Tmdb", "TmdbVoteAverage IS NULL OR TmdbVoteAverage BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.SavedMovieGenre", b =>
                {
                    b.Property<int>("SavedMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbGenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SavedMovieId", "TmdbGenreId");

                    b.HasIndex("TmdbGenreId");

                    b.ToTable("SavedMovieGenre");
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.UserPreferredGenre", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbGenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserProfileId", "TmdbGenreId");

                    b.HasIndex("TmdbGenreId");

                    b.ToTable("UserPreferredGenre");
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MinimumTmdbRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("PreferredReleaseYearFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreferredReleaseYearTo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profile_Id", "Id = 1");

                            t.HasCheckConstraint("CK_Profile_Name", "length(trim(DisplayName)) BETWEEN 2 AND 50");

                            t.HasCheckConstraint("CK_Profile_Rating", "MinimumTmdbRating IS NULL OR MinimumTmdbRating BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_Profile_Years", "(PreferredReleaseYearFrom IS NULL OR PreferredReleaseYearFrom BETWEEN 1888 AND 2100) AND (PreferredReleaseYearTo IS NULL OR PreferredReleaseYearTo BETWEEN 1888 AND 2100) AND (PreferredReleaseYearFrom IS NULL OR PreferredReleaseYearTo IS NULL OR PreferredReleaseYearFrom <= PreferredReleaseYearTo)");
                        });
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.SavedMovie", b =>
                {
                    b.HasOne("FilmRadar.Web.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.SavedMovieGenre", b =>
                {
                    b.HasOne("FilmRadar.Web.Domain.SavedMovie", null)
                        .WithMany("Genres")
                        .HasForeignKey("SavedMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmRadar.Web.Domain.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("TmdbGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.UserPreferredGenre", b =>
                {
                    b.HasOne("FilmRadar.Web.Domain.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("TmdbGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmRadar.Web.Domain.UserProfile", null)
                        .WithMany("PreferredGenres")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.SavedMovie", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("FilmRadar.Web.Domain.UserProfile", b =>
                {
                    b.Navigation("PreferredGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
